# Generated by Django 4.2.3 on 2023-09-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_tb',
            name='Password',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='admin_tb',
            name='Username',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
