# Generated by Django 4.2.3 on 2023-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_admin_tb_password_admin_tb_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbyname_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbyname', models.CharField(max_length=20)),
            ],
        ),
    ]
