# Generated by Django 4.2.3 on 2023-10-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_customerhobby_factor_tb'),
        ('siteadmin', '0006_seasonfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasoncountry_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(max_length=20)),
                ('Countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country_tb')),
                ('Seasonfactorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasonfactor_tb')),
                ('Seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.season_tb')),
                ('Stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.state_tb')),
            ],
        ),
    ]
