# Generated by Django 4.2.3 on 2023-10-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_alter_seasoncountry_tb_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='agefact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimumage', models.IntegerField()),
                ('Maximumage', models.IntegerField()),
                ('Factorname', models.CharField(max_length=20)),
            ],
        ),
    ]
