# Generated by Django 5.0.1 on 2024-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_agefact_tb'),
        ('user', '0015_remove_customerfactor_tb_factorid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agefact_tb',
        ),
        migrations.AlterField(
            model_name='seasoncountry_tb',
            name='Month',
            field=models.CharField(max_length=20),
        ),
    ]
