# Generated by Django 4.2.3 on 2023-09-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_register_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_tb',
            old_name='DOb',
            new_name='DOB',
        ),
    ]
