# Generated by Django 4.2.3 on 2023-10-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_bin_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_tb',
            name='Countryname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
