# Generated by Django 4.2.3 on 2023-10-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_seasoncountry_tb'),
        ('user', '0011_customerhobby_factor_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customerhobby_factor_tb',
            new_name='customerhobbyfactor_tb',
        ),
    ]
