# Generated by Django 4.2.3 on 2023-10-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_agefact_tb'),
        ('user', '0012_rename_customerhobby_factor_tb_customerhobbyfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeragefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.agefact_tb')),
            ],
        ),
    ]
