# Generated by Django 4.2.3 on 2023-10-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0010_agefact_tb'),
        ('user', '0013_customeragefactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasoncountry_tb')),
                ('Userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.register_tb')),
            ],
        ),
    ]
