# Generated by Django 5.0.1 on 2024-03-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_customerfactor_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfactor_tb',
            name='Factorid',
        ),
        migrations.RemoveField(
            model_name='customerfactor_tb',
            name='Userid',
        ),
        migrations.DeleteModel(
            name='customeragefactor_tb',
        ),
        migrations.DeleteModel(
            name='customerfactor_tb',
        ),
    ]
